baseURL = "http://example.org/"
languageCode = "en-us"
title = "DBHealthTech Healthcare IT Consulting"
theme = "pb"
staticDir = ["static"]

[params]
  theme_color = "#2f5c9e"
  description = "description of the best page"
  slogan = "Helping healthcare organizations leverage technology to better meet clinical business needs"
  sub_slogan = "Our staff bring clinical and technical expertise, allowing organizations to focus on the mission and not on technology"
  lead_paragraph = "We understand the challenge of moving your business forward and having the right technology to support it. We provide solutions that allow your staff to focus on performing their job responsiblities and not how to use the technology."
  phone_formatted = "616-359-6555"
  phone = "6163596555"
  address = "DB HealthTech Consulting<br/>377 Benjamin Ave SE<br/>Grand Rapids, MI 49506"
  contact_email = "contact@dbhealthtech.com"
