baseURL = "http://example.org/"
languageCode = "en-us"
title = "DBHealthTech Healthcare IT Consulting"
theme = "pb"
staticDir = ["static"]

[params]
  theme_color = "#4285f4"
  description = "description of the best page"
  slogan = "Helping small to medium-sized healthcare organizations bridge clinical and technology systems"
  sub_slogan = "Specializing in LTPAC including Home Health, Hospice, Skilled Nursing, Senior Living, PACE"
  lead_paragraph = "Bring clinical knowledge to the confusing and complex world of technology in healthcare. Help healthcare organizations focus on the business of delivering care and not on technology"
  phone_formatted = "616-359-6555"
  phone = "6163596555"
  address = "DBHealthTech Consulting<br/>377 Benjamin Ave SE<br/>Grand Rapids, MI 49506"
  contact_email = "contact@dbhealthtech.com"
